# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Mon\QcmBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: {class: Mon\QcmBundle\Entity\User, property: email}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            switch_user: true
            form_login:
                check_path: mon_qcm_security_check
                login_path: mon_qcm_security_login
            logout:
                path:   mon_qcm_security_logout
                target: mon_qcm_homepage
            anonymous: ~
            remember_me:
                key: "%secret%"
                lifetime: 31536000  # 1 year
                path: /
                domain: ~

    access_control:
        - { path: ^/(login|contact|register)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Always the last one
        - { path: ^/, roles: ROLE_USER }